name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  elmRootDirectory:
    description: 'The directory where elm.json is.'
    required: false
    default: '.'
runs:
  using: 'node12'
  main: 'lib/main.js'
