name: 'Test typescript-action'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: npm install
        run: npm ci
      - name: Compile TypeScript
        run: npm run build
      - run: npm test
      - uses: ./
        with:
          elm_root_directory: 'test-repo'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
